// GENERATED by tools/make_selftest_page.py -- do not edit.
// Layout of raiden2_selftest_page.sv, included by raiden2_selftest.sv
// so the two can never disagree about where anything sits.

localparam logic [5:0]  CHK_ROW0        = 6'd3;
localparam int          N_CHECKS        = 22;
localparam logic [6:0]  RESULT_COL      = 7'd32;
localparam logic [5:0]  SUMMARY_ROW     = 6'd25;
localparam logic [6:0]  COUNT_COL       = 7'd10;
localparam logic [5:0]  DETAIL_ROW      = 6'd26;
localparam logic [6:0]  DETAIL_PORT_COL = 7'd22;
localparam logic [6:0]  DETAIL_HEX_COL  = 7'd30;
localparam logic [5:0]  MODE_ROW        = 6'd27;
localparam logic [6:0]  MODE_HEX_COL    = 7'd22;
localparam logic [5:0]  BUILD_ROW       = 6'd28;
localparam logic [6:0]  BUILD_HEX_COL   = 7'd9;
localparam logic [5:0]  HINT_ROW        = 6'd29;
localparam logic [5:0]  TITLE_ROW       = 6'd1;
localparam logic [6:0]  PC_COL          = 7'd25;
